server:
  port: :8080

postgres:
  host: "b7dea484-e154-4352-99fe-147b0c320e9e.hsvc.ir"
  port: 30610
  username: "postgres"
  password: "1fBoSf1G3OMw6TId4X7lwNOdvVI7lWEy"
  database: "request_service"
  autocreate: true

rabbitmq:
  host: "6d6af152-154d-4e83-ac9e-b3e4a9df1888.hsvc.ir"
  port: 32457
  username: "rabbitmq"
  password: "geOvdPR7GkwU4XbjlSAuFnsOc7fpnhjm"

minio:
  endpoint: "my-minio.darkube.app"
  accesskey: "FMZUSsvTowhC0yAmLWgF"
  secretkey: "IUbj0P1ZcK00LfmhsGvYc4MaiONiiu2WLoi8drU0"
  bucket: "request1"
