server:
  port: :8080

postgres:
  host: "b7dea484-e154-4352-99fe-147b0c320e9e.hsvc.ir"
  port: 30610
  username: "postgres"
  password: "1fBoSf1G3OMw6TId4X7lwNOdvVI7lWEy"
  database: "request_service"
  autocreate: true

rabbitmq:
  host: "3e1490dd-1fe3-47e6-99d1-7b3f48de5baa.hsvc.ir"
  port: 32451
  username: "rabbitmq"
  password: "x2OB57JDq6DjHIsqM3WaFLAHQRkDGQCW"

minio:
  endpoint: "my-minio.darkube.app"
  accesskey: "FMZUSsvTowhC0yAmLWgF"
  secretkey: "IUbj0P1ZcK00LfmhsGvYc4MaiONiiu2WLoi8drU0"
  bucket: "request1"
