postgres:
  host: "b7dea484-e154-4352-99fe-147b0c320e9e.hsvc.ir"
  port: 30610
  username: "postgres"
  password: "1fBoSf1G3OMw6TId4X7lwNOdvVI7lWEy"
  database: "request_service"
  autocreate: true

rabbitmq:
  host: "6d6af152-154d-4e83-ac9e-b3e4a9df1888.hsvc.ir"
  port: 32457
  username: "rabbitmq"
  password: "geOvdPR7GkwU4XbjlSAuFnsOc7fpnhjm"

minio:
  endpoint: "my-minio.darkube.app"
  accesskey: "FMZUSsvTowhC0yAmLWgF"
  secretkey: "IUbj0P1ZcK00LfmhsGvYc4MaiONiiu2WLoi8drU0"
  bucket: "request1"

huggingface:
  apikey: "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"
  url: "https://api-inference.huggingface.co/models/ZB-Tech/Text-to-Image"

email:
  apikey: "mlsn.270bbb37ad9a7bd723e9a3eef644b9c091fb230d77b6164d4a892c9b01a3cdfc"
  from: "info@trial-ynrw7gy20nk42k8e.mlsender.net"